### PR TITLE
Intake

### PR DESCRIPTION
**Pull request by rblumin24**
Merging intake subsystem + intake commands into main

### CODE REVIEW

**Comment by AlisonGunzler** [comment]
im commenting here

**Comment by clocko3** [comment]
> im commenting here

so. true.

**Review by clocko3 — CHANGES_REQUESTED** [review]
this is cringe.

**Comment by rblumin24** [comment]
> > im commenting here
> 
> so. true.

wowza

**Review by edf42001 — CHANGES_REQUESTED** [review]
Test slew rate limiter! (also indentation is weird)

**Review by hschilling — COMMENTED** [review]
Double check solenoid port ids

**Comment by rblumin24** [comment]
> this is cringe.

ur face is cringe

**Review by MaisieY587 — CHANGES_REQUESTED** [review]
hi

**Comment by AlisonGunzler** [comment]
> this is cringe

no u

**Comment by clocko3** [comment]
> > this is cringe.
> 
> ur face is cringe

just say ur in love with me and leave loser

**Review by edf42001 — CHANGES_REQUESTED** [review]
Let's get rid of the shooter and navx file, and adjust the value of 0.5 from the rate to a more large value (so the intake isn't too slow)

**Pull request merged**
